version: '3'
services:
  mysql:
    image: mysql:5.7.19
    container_name: mojipic-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  redis:
    image: redis:4.0.1
    container_name: mojipic-redis
    ports:
      - 6379:6379
